import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { mockApp } from './mock'

const nav = (page: Page, name: string) => page.getByRole('navigation', { name: 'Sections' }).getByRole('button', { name, exact: true })
const select = (page: Page, name: string) => page.getByRole('checkbox', { name: `Select ${name}`, exact: true }).check()
const calls = (page: Page, channel: string) => page.evaluate(channel => (window as any).__mock.calls.filter((c: any) => c.channel === channel), channel)

test('selection is visible, filter-aware, and cleared after removal and locking', async ({ page }) => {
  await mockApp(page)
  await select(page, 'Orbit')
  await select(page, 'Nova')
  await expect(page.getByText('2 selected', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search accounts' }).fill('Echo')
  await expect(page.getByText('2 selected outside this filter')).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await page.evaluate(() => {
    const m = (window as any).__mock
    m.data.accounts = m.data.accounts.filter((a: any) => a.userId !== 1)
    m.emit('data:changed', m.data)
  })
  await expect(page.getByText('1 selected', { exact: true })).toBeVisible()
  await nav(page, 'Lock').click()
  await expect(page.getByRole('heading', { name: 'Vault locked' })).toBeVisible()
  await page.getByRole('button', { name: 'Unlock', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Select Nova', exact: true })).not.toBeChecked()
})

test('select visible preserves other selections and empty search offers recovery', async ({ page }) => {
  await mockApp(page)
  await select(page, 'Orbit')
  await page.getByRole('textbox', { name: 'Search accounts' }).fill('Nova')
  await page.getByRole('checkbox', { name: 'Select all visible accounts' }).check()
  await expect(page.getByText('2 selected', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search accounts' }).fill('NoSuchAccount')
  await page.getByRole('button', { name: 'Clear filters' }).click()
  await expect(page.getByRole('checkbox', { name: 'Select Orbit', exact: true })).toBeChecked()
  await expect(page.getByRole('checkbox', { name: 'Select Nova', exact: true })).toBeChecked()
})

test('a pasted experience URL launches once with only accounts that have sessions', async ({ page }) => {
  await mockApp(page)
  await page.getByRole('checkbox', { name: 'Select all visible accounts' }).check()
  await page.getByRole('textbox', { name: 'Experience', exact: true }).fill('https://www.roblox.com/games/2753915549/Blox-Fruits?foo=123')
  await page.evaluate(() => { (window as any).__mock.delays['launch:many'] = 1200 })
  const launch = page.getByRole('button', { name: 'Launch 2 accounts', exact: true })
  await launch.click()
  await expect(launch).toBeDisabled()
  await nav(page, 'Games').click()
  await expect(page.locator('.game-actions').getByRole('button', { name: 'Launch', exact: true })).toBeDisabled()
  await expect.poll(() => calls(page, 'launch:many')).toHaveLength(1)
  const [call] = await calls(page, 'launch:many')
  expect(call.args).toEqual([[1, 2], { placeId: 2753915549, jobId: undefined }])
})

test('missing and expired sessions never enable launch or fall back to a different account', async ({ page }) => {
  await mockApp(page)
  await select(page, 'Atlas')
  await page.getByRole('textbox', { name: 'Experience', exact: true }).fill('2753915549')
  await expect(page.locator('.launch-card').getByRole('button', { name: 'Launch', exact: true })).toBeDisabled()
  await page.getByRole('combobox', { name: 'Account for recent games' }).selectOption('1')
  await expect(page.getByRole('button', { name: 'Launch Adopt Me!', exact: true })).toBeDisabled()
  await nav(page, 'Games').click()
  await expect(page.locator('.game-actions').getByRole('button', { name: 'Launch', exact: true })).toBeDisabled()
  await nav(page, 'Private servers').click()
  await expect(page.getByRole('button', { name: 'Join', exact: true })).toBeDisabled()
})

test('favourite launches preserve the saved Job ID', async ({ page }) => {
  await mockApp(page)
  await select(page, 'Orbit')
  await nav(page, 'Games').click()
  await page.locator('.game-actions').getByRole('button', { name: 'Launch', exact: true }).click()
  const [call] = await calls(page, 'launch:many')
  expect(call.args).toEqual([[1], { placeId: 2753915549, jobId: 'saved-job' }])
})

test('changing experience clears server results and ignores an older response', async ({ page }) => {
  await mockApp(page)
  await select(page, 'Orbit')
  await nav(page, 'Servers').click()
  const place = page.getByRole('textbox', { name: 'Experience link or Place ID' })
  await place.fill('2753915549')
  await page.getByRole('button', { name: 'Load servers', exact: true }).click()
  await expect(page.getByText('server-a', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Full', exact: true })).toBeDisabled()
  await page.evaluate(() => { (window as any).__mock.delays['game:servers'] = 700 })
  await page.getByRole('button', { name: 'Load servers', exact: true }).click()
  await place.fill('920587237')
  await expect(page.getByText('server-a', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Join', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Load servers', exact: true }).click()
  await expect(page.getByText('server-a', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Join', exact: true }).click()
  expect((await calls(page, 'launch:many'))[0].args[1]).toEqual({ placeId: 920587237, jobId: 'server-a' })
})

test('failed search clears stale results and provides retry', async ({ page }) => {
  await mockApp(page)
  await nav(page, 'Games').click()
  await page.getByRole('button', { name: 'Search', exact: true }).click()
  await page.getByRole('textbox', { name: 'Search Roblox games' }).fill('Doors')
  await page.getByRole('button', { name: 'Search', exact: true }).last().click()
  await expect(page.getByText('Doors', { exact: true })).toBeVisible()
  await page.evaluate(() => { (window as any).__mock.failures['game:search'] = 'Offline' })
  await page.getByRole('textbox', { name: 'Search Roblox games' }).fill('Brookhaven')
  await page.getByRole('button', { name: 'Search', exact: true }).last().click()
  await expect(page.getByText('Doors', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Search unavailable', { exact: true })).toBeVisible()
  await page.evaluate(() => { delete (window as any).__mock.failures['game:search'] })
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByText('Brookhaven', { exact: true })).toBeVisible()
})

test('dialog keeps keyboard focus, typing does not reset it, Escape returns to trigger', async ({ page }) => {
  await mockApp(page)
  await nav(page, 'Private servers').click()
  const trigger = page.getByRole('button', { name: 'Add link', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Add a private server' })
  await dialog.getByRole('textbox', { name: 'Share link' }).fill('https://www.roblox.com/share?code=test-code&type=Server')
  await expect(dialog.getByRole('textbox', { name: 'Share link' })).toBeFocused()
  await page.evaluate(() => document.getElementById('account-search')?.focus())
  await expect(dialog.getByRole('textbox', { name: 'Share link' })).toBeFocused()
  for (let i = 0; i < 9; i++) {
    await page.keyboard.press('Tab')
    // Native dialogs may give focus to browser chrome, but never to background controls.
    expect(await dialog.evaluate(el => el.contains(document.activeElement) || document.activeElement === document.body)).toBe(true)
  }
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
})

test('failed favourite save keeps the draft and reports the error inside the dialog', async ({ page }) => {
  await mockApp(page)
  await nav(page, 'Games').click()
  await page.getByRole('button', { name: 'Edit Blox Fruits', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit favourite' })
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('My favourite game')
  await page.evaluate(() => { (window as any).__mock.failures['preset:save'] = 'Could not save. Try again.' })
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Could not save')
  await expect(dialog.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('My favourite game')
  await page.evaluate(() => { delete (window as any).__mock.failures['preset:save'] })
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByText('My favourite game', { exact: true })).toBeVisible()
})

test('startup failure can be retried and event listeners do not duplicate notifications', async ({ page }) => {
  await mockApp(page, { failStartup: true })
  await expect(page.getByRole('heading', { name: 'Could not open TrapRAM' })).toBeVisible()
  await page.evaluate(() => { (window as any).__mock.options.failStartup = false })
  await page.getByRole('button', { name: 'Try again' }).click()
  await expect(page.getByRole('heading', { name: 'Accounts', exact: false })).toBeVisible()
  await page.evaluate(() => (window as any).__mock.emit('toast', 'One notification'))
  await expect(page.getByText('One notification', { exact: true })).toHaveCount(1)
})

test('onboarding exposes each sign-in method', async ({ page }) => {
  await mockApp(page, { empty: true })
  await page.getByRole('button', { name: 'Add your first account' }).click()
  const dialog = page.getByRole('dialog', { name: 'Add an account', exact: true })
  await expect(dialog.getByRole('button', { name: /Sign in to several accounts/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Add account', exact: true }).click()
  await dialog.getByRole('button', { name: /Paste a .ROBLOSECURITY cookie/ }).click()
  await expect(page.getByRole('textbox', { name: 'Session cookie' })).toBeFocused()
})

test('account actions work by keyboard, retain failed edits, and restore focus', async ({ page }) => {
  await mockApp(page)
  const actions = page.getByRole('button', { name: 'Actions for Orbit', exact: true })
  await actions.focus()
  await page.keyboard.press('Enter')
  const menu = page.getByRole('group', { name: 'Account actions' })
  await expect(menu.getByRole('button', { name: 'Open browser as this account' })).toBeFocused()
  await expect(menu.getByRole('button', { name: 'Move down', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(actions).toBeFocused()
  await actions.click()
  await menu.getByRole('button', { name: 'Edit alias, group, note' }).click()
  const dialog = page.getByRole('dialog', { name: 'Orbit', exact: true })
  await dialog.getByRole('textbox', { name: 'Alias', exact: true }).fill('My main')
  await page.evaluate(() => { (window as any).__mock.failures['account:update'] = 'Could not save. Try again.' })
  await dialog.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog.getByRole('textbox', { name: 'Alias', exact: true })).toHaveValue('My main')
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  expect(results.violations.map(v => v.id)).toEqual([])
})

test('failed server save retains inputs and deletion can be cancelled', async ({ page }) => {
  await mockApp(page)
  await nav(page, 'Private servers').click()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: 'Delete Friends only' }).click()
  expect(await calls(page, 'server:remove')).toHaveLength(0)
  await page.getByRole('button', { name: 'Add link', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add a private server' })
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('Weekend server')
  await dialog.getByRole('textbox', { name: 'Share link', exact: true }).fill('https://www.roblox.com/share?code=test-code')
  await page.evaluate(() => { (window as any).__mock.failures['server:save'] = 'Could not save. Try again.' })
  await dialog.getByRole('button', { name: 'Resolve and save' }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Weekend server')
})

test('system theme follows the OS and error notifications remain until dismissed', async ({ page }) => {
  await mockApp(page)
  await nav(page, 'Settings').click()
  await page.getByRole('button', { name: 'System', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.clock.install()
  await page.evaluate(() => (window as any).__mock.emit('toast:warn', 'Could not finish. Try again.'))
  await page.clock.fastForward(10_000)
  await expect(page.getByRole('alert')).toContainText('Could not finish')
  await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
})

for (const theme of ['dark', 'light'] as const) {
  for (const width of [1180, 320]) {
    test(`all sections reflow and pass automated accessibility checks: ${theme}, ${width}px`, async ({ page }, testInfo) => {
      await page.setViewportSize({ width, height: 900 })
      const errors: string[] = []
      page.on('pageerror', error => errors.push(error.message))
      await mockApp(page)
      await nav(page, 'Settings').click()
      await page.getByRole('button', { name: theme === 'dark' ? 'Dark' : 'Light', exact: true }).click()
      await select(page, 'Orbit')
      for (const section of ['Launch', 'Games', 'Servers', 'Private servers', 'Performance', 'Settings']) {
        await nav(page, section).click()
        const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
        expect(results.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, summary: n.failureSummary })) })), section).toEqual([])
        const overflow = await page.evaluate(() => [...document.querySelectorAll<HTMLElement>('main, .app-workspace, .main-scroll, .modal')].filter(e => e.offsetWidth && e.scrollWidth > e.clientWidth + 1).map(e => e.className))
        expect(overflow, section).toEqual([])
      }
      await nav(page, 'Launch').click()
      await page.screenshot({ path: testInfo.outputPath(`workspace-${theme}-${width}.png`) })
      expect(errors).toEqual([])
    })
  }
}

test('reduced motion disables animations and press transforms', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await mockApp(page)
  await page.getByRole('button', { name: 'Add account', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Add an account', exact: true })
  expect(await dialog.evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  expect(await dialog.evaluate(el => getComputedStyle(el).transitionDuration)).toBe('0s')
})
